/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.File;
import javax.swing.*;
/**
 *
 * @author J_Alonso
 */
public class MainApp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainApp.class.getName());
    private File archivoActual;

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_titulo = new java.awt.Label();
        txt_palabras = new java.awt.TextArea();
        btn_Procesar = new javax.swing.JButton();
        l_total = new javax.swing.JLabel();
        l_longitud = new javax.swing.JLabel();
        l_Primeraletra = new javax.swing.JLabel();
        l_Ultimaletra = new javax.swing.JLabel();
        l_Letracentral = new javax.swing.JLabel();
        l_Primerapalabra = new javax.swing.JLabel();
        l_Palabracentral = new javax.swing.JLabel();
        l_Ultimapalabra = new javax.swing.JLabel();
        l_tituloDos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        i_txt_murcielago = new javax.swing.JTextPane();
        i_total = new javax.swing.JTextField();
        i_longitud = new javax.swing.JTextField();
        i_ultima_letra = new javax.swing.JTextField();
        i_primera_letra = new javax.swing.JTextField();
        i_letra_central = new javax.swing.JTextField();
        i_palabra_central = new javax.swing.JTextField();
        i_primera_palabra = new javax.swing.JTextField();
        i_ultima_palabra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        i_Rept_A = new javax.swing.JTextField();
        i_Rept_E = new javax.swing.JTextField();
        i_Rept_I = new javax.swing.JTextField();
        i_Rept_O = new javax.swing.JTextField();
        i_Rept_U = new javax.swing.JTextField();
        i_palabras_par = new javax.swing.JTextField();
        i_palabras_impar = new javax.swing.JTextField();
        JMenuBar = new javax.swing.JMenuBar();
        M_Archivo = new javax.swing.JMenu();
        i_abrir = new javax.swing.JMenuItem();
        i_Guardar = new javax.swing.JMenuItem();
        i_GuardarComo = new javax.swing.JMenuItem();
        M_Editar = new javax.swing.JMenu();
        i_Copiar = new javax.swing.JMenuItem();
        i_Cortar = new javax.swing.JMenuItem();
        i_Pegar = new javax.swing.JMenuItem();
        i_Buscar = new javax.swing.JMenuItem();
        i_Remplazar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        l_titulo.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_titulo.setForeground(new java.awt.Color(255, 255, 255));
        l_titulo.setText("Manejo de Cadena");

        btn_Procesar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Procesar.setFont(new java.awt.Font("Segoe UI Symbol", 3, 12)); // NOI18N
        btn_Procesar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Procesar.setText("Procesar");
        btn_Procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProcesarActionPerformed(evt);
            }
        });

        l_total.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_total.setForeground(new java.awt.Color(255, 255, 255));
        l_total.setText("Total de Palabras ");

        l_longitud.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_longitud.setForeground(new java.awt.Color(255, 255, 255));
        l_longitud.setText("Longitud del Texto");

        l_Primeraletra.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_Primeraletra.setForeground(new java.awt.Color(255, 255, 255));
        l_Primeraletra.setText("Primera letra del texto");

        l_Ultimaletra.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_Ultimaletra.setForeground(new java.awt.Color(255, 255, 255));
        l_Ultimaletra.setText("Ultima letra del texto");

        l_Letracentral.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_Letracentral.setForeground(new java.awt.Color(255, 255, 255));
        l_Letracentral.setText("Letra central del texto");

        l_Primerapalabra.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_Primerapalabra.setForeground(new java.awt.Color(255, 255, 255));
        l_Primerapalabra.setText("Primera Palabra");

        l_Palabracentral.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_Palabracentral.setForeground(new java.awt.Color(255, 255, 255));
        l_Palabracentral.setText("Palabra Central");

        l_Ultimapalabra.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_Ultimapalabra.setForeground(new java.awt.Color(255, 255, 255));
        l_Ultimapalabra.setText("Ultima Palabra");

        l_tituloDos.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        l_tituloDos.setForeground(new java.awt.Color(255, 255, 255));
        l_tituloDos.setText("Traduccion a Clave Murcielago");

        jScrollPane1.setViewportView(i_txt_murcielago);

        i_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_totalActionPerformed(evt);
            }
        });

        i_longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_longitudActionPerformed(evt);
            }
        });

        i_ultima_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_ultima_letraActionPerformed(evt);
            }
        });

        i_primera_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_primera_letraActionPerformed(evt);
            }
        });

        i_letra_central.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_letra_centralActionPerformed(evt);
            }
        });

        i_palabra_central.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_palabra_centralActionPerformed(evt);
            }
        });

        i_primera_palabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_primera_palabraActionPerformed(evt);
            }
        });

        i_ultima_palabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_ultima_palabraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Repeticiones de \"A\" , \"a\" ó \"á\":");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Repeticiones de \"I\" , \"i\" ó \"í\":");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Repeticiones de \"E\" , \"e\" ó \"é\":");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Repeticiones de \"O\" , \"o\" ó \"ó\":");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Repeticiones de \"U\" , \"u\" ó \"ú\":");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Palabras con Cantidad de Caracteres par:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Palabras con Cantidad de Caracteres impar:");

        i_Rept_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_Rept_AActionPerformed(evt);
            }
        });

        i_palabras_impar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_palabras_imparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(l_Ultimapalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i_ultima_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_Primeraletra, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_Palabracentral, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_Primerapalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_Letracentral, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_total, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_Ultimaletra, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i_primera_palabra)
                            .addComponent(i_letra_central)
                            .addComponent(i_ultima_letra)
                            .addComponent(i_palabra_central, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(i_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i_total)
                            .addComponent(i_primera_letra))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Procesar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_tituloDos)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i_Rept_A, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(i_palabras_par)
                                .addComponent(i_palabras_impar)
                                .addComponent(i_Rept_U)
                                .addComponent(i_Rept_O)
                                .addComponent(i_Rept_E)
                                .addComponent(i_Rept_I, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_palabras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Procesar)
                    .addComponent(l_tituloDos))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(i_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_longitud))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(i_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_total))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(i_primera_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_Primeraletra))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(i_ultima_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_Ultimaletra))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(i_letra_central, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_Letracentral))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(i_primera_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_Primerapalabra))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(i_palabra_central, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_Palabracentral))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(i_ultima_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_Ultimapalabra)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(i_Rept_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(i_Rept_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(i_Rept_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(i_Rept_O, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(i_Rept_U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(i_palabras_par, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(i_palabras_impar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 181, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        M_Archivo.setText("Archivo");

        i_abrir.setText("Abrir");
        i_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_abrirActionPerformed(evt);
            }
        });
        M_Archivo.add(i_abrir);

        i_Guardar.setText("Guardar");
        i_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_GuardarActionPerformed(evt);
            }
        });
        M_Archivo.add(i_Guardar);

        i_GuardarComo.setText("Guardar Como");
        i_GuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_GuardarComoActionPerformed(evt);
            }
        });
        M_Archivo.add(i_GuardarComo);

        JMenuBar.add(M_Archivo);

        M_Editar.setText("Editar");

        i_Copiar.setText("Copiar");
        i_Copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_CopiarActionPerformed(evt);
            }
        });
        M_Editar.add(i_Copiar);

        i_Cortar.setText("Cortar");
        i_Cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_CortarActionPerformed(evt);
            }
        });
        M_Editar.add(i_Cortar);

        i_Pegar.setText("Pegar");
        i_Pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_PegarActionPerformed(evt);
            }
        });
        M_Editar.add(i_Pegar);

        i_Buscar.setText("Buscar");
        i_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_BuscarActionPerformed(evt);
            }
        });
        M_Editar.add(i_Buscar);

        i_Remplazar.setText("Remplazar");
        i_Remplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_RemplazarActionPerformed(evt);
            }
        });
        M_Editar.add(i_Remplazar);

        JMenuBar.add(M_Editar);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_totalActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_i_totalActionPerformed

    private void i_longitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_longitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_longitudActionPerformed

    private void i_ultima_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_ultima_letraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_ultima_letraActionPerformed

    private void i_primera_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_primera_letraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_primera_letraActionPerformed

    private void i_letra_centralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_letra_centralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_letra_centralActionPerformed

    private void i_palabra_centralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_palabra_centralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_palabra_centralActionPerformed

    private void i_primera_palabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_primera_palabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_primera_palabraActionPerformed

    private void i_ultima_palabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_ultima_palabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_ultima_palabraActionPerformed

    private void i_palabras_imparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_palabras_imparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_palabras_imparActionPerformed

    private void btn_ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProcesarActionPerformed
        // TODO add your handling code here:
        String texto = txt_palabras.getText();
    i_total.setText(String.valueOf(TextoProcesador.contarCaracteres(texto)));
    i_longitud.setText(String.valueOf(TextoProcesador.contarPalabras(texto)));
    i_primera_letra.setText(TextoProcesador.primeraLetra(texto));
    i_ultima_letra.setText(TextoProcesador.ultimaLetra(texto));
    i_letra_central.setText(TextoProcesador.letraCentral(texto));
    i_primera_palabra.setText(TextoProcesador.primeraPalabra(texto));
    i_ultima_palabra.setText(TextoProcesador.ultimaPalabra(texto));
    i_palabra_central.setText(TextoProcesador.palabraCentral(texto));
    i_txt_murcielago.setText(CodigoMurcielago.traducir(texto));
    i_Rept_A.setText(String.valueOf(TextoProcesador.contarOcurrenciasChar(texto, 'a')));
    i_Rept_E.setText(String.valueOf(TextoProcesador.contarOcurrenciasChar(texto, 'e')));
    i_Rept_I.setText(String.valueOf(TextoProcesador.contarOcurrenciasChar(texto, 'i')));
    i_Rept_O.setText(String.valueOf(TextoProcesador.contarOcurrenciasChar(texto, 'e')));
    i_Rept_U.setText(String.valueOf(TextoProcesador.contarOcurrenciasChar(texto, 'u')));
    i_palabras_par.setText(String.valueOf(TextoProcesador.contarPalabrasPares(texto)));
    i_palabras_impar.setText(String.valueOf(TextoProcesador.contarPalabrasImpares(texto)));
    }//GEN-LAST:event_btn_ProcesarActionPerformed

    private void i_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_abrirActionPerformed
                // TODO add your handling code here:
                String contenido = ArchivoManager.abrirArchivo(this);
                 if (contenido != null) {
                    txt_palabras.setText(contenido);
                     }
    }//GEN-LAST:event_i_abrirActionPerformed

    private void i_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_GuardarActionPerformed
        // TODO add your handling code here:
        //String contenido = ArchivoManager(this);
        if (archivoActual != null) {
        ArchivoManager.guardarArchivo(this, txt_palabras.getText(), archivoActual);
    } else {
        archivoActual = ArchivoManager.guardarComo(this, txt_palabras.getText());
    }
    }//GEN-LAST:event_i_GuardarActionPerformed

    private void i_GuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_GuardarComoActionPerformed
        // TODO add your handling code here:
        archivoActual = ArchivoManager.guardarComo(this, txt_palabras.getText());
    }//GEN-LAST:event_i_GuardarComoActionPerformed

    private void i_CopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_CopiarActionPerformed
        // TODO add your handling code here:
       // EditorManager.copiar(txt_palabras);
    }//GEN-LAST:event_i_CopiarActionPerformed

    private void i_PegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_PegarActionPerformed
        // TODO add your handling code here:
      // EditorManager.pegar(txt_palabras);
     
    }//GEN-LAST:event_i_PegarActionPerformed

    private void i_CortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_CortarActionPerformed
        // TODO add your handling code here:
        //EditorManager.cortar(txt_palabras);
    }//GEN-LAST:event_i_CortarActionPerformed

    private void i_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_BuscarActionPerformed
        // TODO add your handling code here:
        String palabra = JOptionPane.showInputDialog(this, "Ingrese palabra a buscar:");
    if (palabra != null && !palabra.isEmpty()) {
        int pos = EditorManager.buscar(txt_palabras, palabra);
        if (pos == -1) {
            JOptionPane.showMessageDialog(this, "No se encontró la palabra.");
        }
    }
    }//GEN-LAST:event_i_BuscarActionPerformed

    private void i_RemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_RemplazarActionPerformed
        // TODO add your handling code here:
         String buscar = JOptionPane.showInputDialog(this, "Palabra a reemplazar:");
    String reemplazar = JOptionPane.showInputDialog(this, "Reemplazar por:");
    if (buscar != null && reemplazar != null) {
       // EditorManager.reemplazar(txt_palabras, buscar, reemplazar);
    }
    }//GEN-LAST:event_i_RemplazarActionPerformed

    private void i_Rept_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_Rept_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_Rept_AActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JMenu M_Archivo;
    private javax.swing.JMenu M_Editar;
    private javax.swing.JButton btn_Procesar;
    private javax.swing.JMenuItem i_Buscar;
    private javax.swing.JMenuItem i_Copiar;
    private javax.swing.JMenuItem i_Cortar;
    private javax.swing.JMenuItem i_Guardar;
    private javax.swing.JMenuItem i_GuardarComo;
    private javax.swing.JMenuItem i_Pegar;
    private javax.swing.JMenuItem i_Remplazar;
    private javax.swing.JTextField i_Rept_A;
    private javax.swing.JTextField i_Rept_E;
    private javax.swing.JTextField i_Rept_I;
    private javax.swing.JTextField i_Rept_O;
    private javax.swing.JTextField i_Rept_U;
    private javax.swing.JMenuItem i_abrir;
    private javax.swing.JTextField i_letra_central;
    private javax.swing.JTextField i_longitud;
    private javax.swing.JTextField i_palabra_central;
    private javax.swing.JTextField i_palabras_impar;
    private javax.swing.JTextField i_palabras_par;
    private javax.swing.JTextField i_primera_letra;
    private javax.swing.JTextField i_primera_palabra;
    private javax.swing.JTextField i_total;
    private javax.swing.JTextPane i_txt_murcielago;
    private javax.swing.JTextField i_ultima_letra;
    private javax.swing.JTextField i_ultima_palabra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_Letracentral;
    private javax.swing.JLabel l_Palabracentral;
    private javax.swing.JLabel l_Primeraletra;
    private javax.swing.JLabel l_Primerapalabra;
    private javax.swing.JLabel l_Ultimaletra;
    private javax.swing.JLabel l_Ultimapalabra;
    private javax.swing.JLabel l_longitud;
    private java.awt.Label l_titulo;
    private javax.swing.JLabel l_tituloDos;
    private javax.swing.JLabel l_total;
    private java.awt.TextArea txt_palabras;
    // End of variables declaration//GEN-END:variables
}
